CC = g++
CFLAGS = -g -Wall

all: quicksort r_quicksort

quicksort: quicksort.cpp
		$(CC) $(CFLAGS) -o quicksort quicksort.cpp

r_quicksort: r_quicksort.cpp
		$(CC) $(CFLAGS) -o r_quicksort r_quicksort.cpp

clean:
	rm quicksort r_quicksort

